# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 419936ce1521279f355541bb19c7353a4caacc2114b73e188081506d47915c273b5a5e8f8fe1237b1907f2843483d75b41cbf7427f4c8313002fd3bd1ef30b7d

test:
  secret_key_base: 5691c8df58144f22abdcf45e88ae07c73f8679427de1935c94f44e1bd2777d3f85bfd3d709960ae093457b1a6c9c210fbbd3d2f1b523b9e5fcca72cd04df9fe1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
